#!/usr/bin/env bash
## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

# Initialize stack
fin project start

# Install project requirements
fin exec composer clear-cache
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec composer install

# Set up blt
cd $DOCROOT_PATH
fin blt blt:init:settings
fin blt drupal:install